### ISSUE TITLE
change url

### ISSUE THREAD

**Issue by andronasef** [Susmita-Dey/Atelas-Esports-Website#2]
you need to change website url from https://susmita-dey.github.io/Gaming-Website/ to https://susmita-dey.github.io/Atelas-Esports-Website/

**Comment by Susmita-Dey** [comment]
> you need to change website url from https://susmita-dey.github.io/Gaming-Website/ to https://susmita-dey.github.io/Atelas-Esports-Website/

Thanks for reminding me.
